spring.application.name=hospital-appointments
server.port=5008
server.servlet.context-path=/hospital
#--------------------DBA CONFIGURATION--------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_appointments
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#---------------------FLYWAY CONFIGURATION----------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration