spring.application.name=hospital-appointments
server.port=5008
server.servlet.context-path=/hospital
#--------------------DBA CONFIGURATION---------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_appointments
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#---------------------FLYWAY CONFIGURATION----------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#---------------------SMTP CONFIGURATION------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#---------------------TLS SMTP MAIL------------------------------------
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.profiles.include=local
#---------------------------LINKS---------------------------------
login.link=http://localhost:3000/login
reset.link=http://localhost:3000/reset-password?code=
