###DATABASE
spring.datasource.password=postgresql

###JWT
jwt.secret.string=lucianospaletti1926202305052245192312
jwt.expiration.time=7846000000

###SMTP#####
spring.mail.username=cipyoprean@gmail.com
spring.mail.password=lwgl mdaa bbop hrka